name: Virtuemart GPE plugin sync with EMS Online
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: Maksym-Kostenko-Leasoft/gpe_ecwid
      - name: checkout
        run: |
          git checkout main
        id: message
      - name: getting_bank_func_from_remote_repository
        run: |
          git clone https://github.com/Maksym-Kostenko-Leasoft/ems-online-ecwid.git
          cd ems-online-ecwid
          git checkout bank_func
          git pull
          sudo cp -r ./* ../
          cd ../
          sudo rm -rf ems-online-ecwid/
          ls -la
  